const CONFIG = {
  KEY: process.env.REACT_APP_API_KEY,
  BASE_URL: process.env.REACT_APP_BASE_URL,
  BASE_IMAGE_URL: process.env.REACT_APP_BASE_IMAGE_URL,
  DEFAULT_LANGUAGE: process.env.REACT_APP_DEFAULT_LANGUAGE,
  CACHE_NAME: process.env.REACT_APP_CACHE_NAME,
};

export default CONFIG;
